allprojects {
    repositories {
        google()
        mavenCentral()
        // You can safely remove the next line in recent Flutter versions
        // maven { url 'https://storage.googleapis.com/download.flutter.io' }
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.set(newBuildDir)

subprojects {
    def newSubprojectBuildDir = newBuildDir.dir(project.name)
    project.layout.buildDirectory.set(newSubprojectBuildDir)
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}